### ISSUE TITLE
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api

### ISSUE THREAD

**Issue by mohamedfarees** [actions/labeler#814] opened 2024-10-23 13:39 UTC
**Description:**
We have upgraded to labeler 5. I have .github/labeler.yml file and .github/workflows/labeler.yml. The action we are using github provided micorsoft 
For all the PR I can see the action and successful but for some PR, upon success im getting this error and labels are not applied

Run actions/labeler@v5
  with:
    repo-token: ***
    configuration-path: .github/labeler.yml
    sync-labels: false
    dot: true
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api

```
2024-10-23T09:26:33.9375145Z Current runner version: '2.320.0'
2024-10-23T09:26:33.9400143Z ##[group]Operating System
2024-10-23T09:26:33.9401212Z Ubuntu
2024-10-23T09:26:33.9401923Z 22.04.5
2024-10-23T09:26:33.9402517Z LTS
2024-10-23T09:26:33.9403130Z ##[endgroup]
2024-10-23T09:26:33.9403997Z ##[group]Runner Image
2024-10-23T09:26:33.9404815Z Image: ubuntu-22.04
2024-10-23T09:26:33.9405538Z Version: 20241015.1.0
2024-10-23T09:26:33.9407289Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20241015.1/images/ubuntu/Ubuntu2204-Readme.md
2024-10-23T09:26:33.9409717Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20241015.1
2024-10-23T09:26:33.9411261Z ##[endgroup]
2024-10-23T09:26:33.9412094Z ##[group]Runner Image Provisioner
2024-10-23T09:26:33.9413014Z 2.0.384.1
2024-10-23T09:26:33.9413684Z ##[endgroup]
2024-10-23T09:26:33.9435157Z ##[group]GITHUB_TOKEN Permissions
2024-10-23T09:26:33.9437363Z Contents: read
2024-10-23T09:26:33.9437792Z Metadata: read
2024-10-23T09:26:33.9438447Z PullRequests: write
2024-10-23T09:26:33.9438945Z ##[endgroup]
2024-10-23T09:26:33.9441308Z Secret source: Actions
2024-10-23T09:26:33.9441999Z Prepare workflow directory
2024-10-23T09:26:34.0061199Z Prepare all required actions
2024-10-23T09:26:34.0215598Z Getting action download info
2024-10-23T09:26:34.1825394Z Download action repository 'actions/labeler@v5' (SHA:generated)
2024-10-23T09:26:34.7233937Z Complete job name: triage
2024-10-23T09:26:34.8077410Z ##[group]Run actions/labeler@v5
2024-10-23T09:26:34.8078008Z with:
2024-10-23T09:26:34.8078604Z   repo-token: ***
2024-10-23T09:26:34.8079486Z   configuration-path: .github/labeler.yml
2024-10-23T09:26:34.8080090Z   sync-labels: false
2024-10-23T09:26:34.8080483Z   dot: true
2024-10-23T09:26:34.8080928Z ##[endgroup]
2024-10-23T09:26:35.9131231Z The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
2024-10-23T09:26:36.1366726Z Cleaning up orphan processes
```

The .github/labeler.yml file
```yml
only-tests:
  - any:
      - changed-files:
          - any-glob-to-any-file: "tests/*"

api:
  - any:
      - changed-files:
          - any-glob-to-any-file: "src/api/*"

web-apps:
  - any:
      - changed-files:
          - any-glob-to-any-file: "src/web/*"

admin-apps:
  - any:
      - changed-files:
          - any-glob-to-any-file: "src/admin/*"

github-workflows:
  - any:
      - changed-files:
          - any-glob-to-any-file: ".github/*"

infrastructure:
  - any:
      - changed-files:
          - any-glob-to-any-file: "infra/*"

repo-config:
  - any:
      - changed-files:
          - any-glob-to-any-file: "*"

dashboard:
  - any:
      - changed-files:
          - any-glob-to-any-file: "src/notebooks/*"
```

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Make change in any mentioned folder and raise PR in default branch where PR is merged in some cases we can see its not populating

**Expected behavior:**
Labels should populate as per above config all the time

**Actual behavior:**
Labels are working rarely and most cases getting above error, eventhough file is present it is not recognizing

**Comment by priyagupta108** [comment] 2024-10-24 04:47
Hi @mohamedfarees 👋,
Thank you for your report. We'll investigate the issue and get back to you with the details!

**Comment by suyashgaonkar** [comment] 2024-11-15 09:43
Hi @mohamedfarees , We investigated the issue with provided information and we confirm that error The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api occurs when the labeler configuration file is not available on the host runner, hence we need to upload it on the runner with help of  @actions/checkout. To resolve the issue you can try following steps in your labeler.yml workflow file.
 steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: '.github/labeler.yml'
        sync-labels: true

You can refer to following link for more details: configuration-path 

Please also refer following screenshot.

![image](https://github.com/user-attachments/assets/01795b7c-680e-4b65-9e5c-7c7dbb37d851)

**Comment by mohamedfarees** [comment] 2024-11-15 11:23
Thanks for the info as work around I tried ** instead of * in labeler.yml for those folder and it works fine till now. 

In case if I face any issues I will implement the above step that yml by adding checkout in it

**Comment by suyashgaonkar** [comment] 2024-11-19 08:23
Hi @mohamedfarees, Thank you for the response as it looks like the issue is resolved. We are closing the ticket, you can let us know if you still need any assistance on this.

**Closed by suyashgaonkar** 2024-11-19 08:23 UTC
Labels: bug
