### ISSUE TITLE
Expose the `labels` as action output

### ISSUE THREAD

**Issue by daczarne** [actions/labeler#407] opened 2022-07-25 23:50 UTC
Currently the action generates the `labels` attributes and sends it to the GitHub API. It would be nice to have it also as an output of the action.

**Comment by MaksimZhukov** [comment] 2022-12-12 09:26
Hello @daczarne ! 
I am closing this issue as a duplicate of [this one](https://github.com/actions/labeler/issues/59). Please monitor the feature status in scope of that issue.

**Closed by MaksimZhukov** 2022-12-12 09:26 UTC
