### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by duffzm** [actions/labeler#662] opened 2023-08-29 18:18 UTC
**Description:**
I'm not seeing any output (`new-labels`, `all-labels`) from use of the action. Otherwise, my labels are being synchronized correctly.

**Action version:**
v4 (note that @v4.3.0 shows as not found for me, not sure if it matters)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  

```yaml
jobs:
  setup:
    runs-on: [ self-hosted, ECSRunner]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add Labels
        id: add-label
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.CICD_PAT }}
          sync-labels: true
      - name: Print all labels
        run: |
          echo "${{ toJSON(steps.add-label.outputs) }}"
          echo "${{ steps.add-label.outputs }}"
          echo "${{ steps.add-label.outputs.all-labels }}"
          echo "${{ steps.add-label.outputs.new-labels }}"
          echo "${{ toJSON(steps.add-label.outputs.all-labels) }}"
```

labeler.yml file

```yaml
AnyChange:
  - '**'
  
MyOtherLabels:
  - 'app/**'
  
 etc.
```
**Expected behavior:**
I expect to have non null ouput containing sync'd label values.

**Actual behavior:**
this 
```yaml
jobs:
  setup:
    runs-on: [ self-hosted, NoDocker ]
    outputs:
      timeout_minutes: ${{ env.TIMEOUT_MINUTES }}
      pr_labels: ${{ env.PR_LABELS }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Job Init
        uses: data-products-and-platforms/actions/job-init@main
      - name: Add Labels
        id: add-label
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.CICD_PAT }}
          sync-labels: true
      - name: Print all labels
        run: |
          echo "${{ toJSON(steps.add-label.outputs) }}"
          echo "${{ steps.add-label.outputs }}"
          echo "${{ steps.add-label.outputs.all-labels }}"
          echo "${{ steps.add-label.outputs.new-labels }}"
          echo "${{ toJSON(steps.add-label.outputs.all-labels) }}"
```
results in:
```
0s
Run echo "{}"
  echo "{}"
  echo "Object"
  echo ""
  echo ""
  echo "null"
  shell: /bin/bash -e {0}
{}
Object


null
```
but labeling is working
<img width="132" alt="image" src="https://github.com/actions/labeler/assets/52840376/fd106b8c-241d-4b92-bafe-b84836d03004">

**Comment by duffzm** [comment] 2023-08-29 18:42
Note that can't point to a specific release number, only `v4`. Example: 
```
Error: Unable to resolve action `GitHub-Public-Actions/labeler@v4.3.0`, unable to find version `v4.3.0`
```

**Comment by MaksimZhukov** [comment] 2023-08-30 06:44
Hello @duffzm!
We will investigate the issue!

**Comment by MaksimZhukov** [comment] 2023-09-25 11:26
Hello @duffzm!
I could not reproduce your issue, everything works as expected ([workflow](https://github.com/MaksimZhukov/labeler-issue/blob/main/.github/workflows/test-outputs.yml), [pull request](https://github.com/MaksimZhukov/labeler-issue/pull/1), [workflow run](https://github.com/MaksimZhukov/labeler-issue/actions/runs/6298474735/job/17097398062#step:3:1)).

Do you use GitHub Enterprise Server? If so, I think updating the actions that are bundled with your enterprise will solve the issue. Please refer to the following documentation:
1) [About using actions in your enterprise](https://docs.github.com/en/enterprise-server@3.6/admin/github-actions/managing-access-to-actions-from-githubcom/about-using-actions-in-your-enterprise)
2) [Using the latest version of the official bundled actions](https://docs.github.com/en/enterprise-server@3.6/admin/github-actions/managing-access-to-actions-from-githubcom/using-the-latest-version-of-the-official-bundled-actions)

**Comment by MaksimZhukov** [comment] 2023-09-29 11:57
@duffzm just a gentle reminder

**Comment by duffzm** [comment] 2023-10-04 04:31
Would you mind editing your workflow from
```
      uses: actions/labeler@v4.3.0
```
to 
```
      uses: actions/labeler@v4
```
just want to verify `v4` is working as expected for us. But yeah, sounds like you're right.

**Comment by MaksimZhukov** [comment] 2023-10-19 14:24
I have checked it with `v4` ([workflow file](https://github.com/MaksimZhukov/labeler-issue/actions/runs/6576010898/workflow), [workflow run](https://github.com/MaksimZhukov/labeler-issue/actions/runs/6576010898/job/17864437098#step:4:9)), everything works as expected.
I am closing the issue. Feel free to contact us if you have any questions!

**Closed by MaksimZhukov** 2023-10-19 14:24 UTC
Labels: bug
