### ISSUE TITLE
HttpError: API rate limit exceeded

### ISSUE THREAD

**Issue by austince** [actions/labeler#448] opened 2022-10-12 15:49 UTC
We're seeing consistent rate limit exceeded errors from this action in our reasonably (~50 runs a day), starting from just a few days ago. Is it possible 4.0.2 increased the load in some way? 

<img width="596" alt="Screen Shot 2022-10-10 at 16 20 24" src="https://user-images.githubusercontent.com/4655775/195380376-1dedb846-b5f8-40d5-b7d4-459d812472d8.png">

**Comment by MaksimZhukov** [comment] 2022-11-02 15:32
Hello @austince !
Could you please provide us with a link to the public repository where the issue occurs for further investigation if you are still facing it?

**Comment by austince** [comment] 2022-11-02 15:36
Hey there, not a public repo, unfortunately. We've limited the workflow triggers to just when PRs are created, which seems to help, but may not be an acceptable solution for all projects. 

```yaml
on:
  pull_request_target:
    types: [ created ]
```

**Comment by infinisil** [comment] 2023-01-20 21:56
I just ran into this for https://github.com/NixOS/nixpkgs/pull/211832

**Comment by dusan-trickovic** [comment] 2023-05-30 11:38
Hello, @austince ! Thank you for reaching out! I apologize for the late response. If that's alright, I would like to ask you to provide me with some additional context regarding this problem.

First, if you could, please provide a more detailed description of what seems to be wrong. As for limiting triggers, that could definitely help take some load off of the server processing those requests - as long as it complies with the specific needs of you or your organization.

However, there is another suggestion that could make spotting the problem a bit easier:

- Since your original repo isn't public, it could be very helpful if you could create some minimal public repository with a sample workflow that threw this error for you. That way, we can potentially spot where the issue is, identify its culprit and eventually come up with a viable solution.

Thank you very much for your patience and cooperation :)

**Comment by infinisil** [comment] 2023-06-06 15:54
@dusan-trickovic See the above open-source PR I linked, it happened there too. Here's a workflow run that failed because of this error: https://github.com/NixOS/nixpkgs/actions/runs/3971508163

**Comment by dusan-trickovic** [comment] 2023-06-12 22:45
Hello @infinisil ! Thank you for letting us know about it. I just wanted to ask if you are still experiencing this error? If so, could you provide us with a more recent action run (since the logs and contents of the one you attached have since expired and are no longer available for viewing)? Thank you again for your cooperation :)

**Comment by dusan-trickovic** [comment] 2023-06-16 10:20
Hi @infinisil ! Sorry, just giving you a gentle ping to see if there are any updates on your end? Thank you! :)

**Comment by infinisil** [comment] 2023-06-16 10:24
I don't have a more recent action run right now, I'll let you know when I do. I'm pretty sure it was caused by just having too many changes and labels trying to be added, because the above-linked PR moves about ~12k files around 😅

**Comment by dusan-trickovic** [comment] 2023-06-16 10:45
@infinisil thank you! In that case, I'm going to close this issue. If the problem occurs again, please let us know and we will reopen this issue for further investigation.

As always, thank you for the cooperation :)

**Closed** 2023-06-16 10:46 UTC
Labels: bug
