### ISSUE TITLE
Existing labels get removed even with `sync-labels: false`

### ISSUE THREAD

**Issue by akihironitta** [actions/labeler#404] opened 2022-07-19 01:35 UTC
### A possible misbehaviour

Existing labels get removed even configured with:
```yml
sync-labels: false  # which is the default
```

In our repository, we see that the labeler removes an existing label right after the label gets added to an PR by one of our maintainers as observed in https://github.com/Lightning-AI/lightning/pull/13703.

### Our configuration

- labeler caller: https://github.com/Lightning-AI/lightning/blob/35ec79ad1f75790767a6857637c9bbe052e47b58/.github/workflows/labeler.yml
- labeler filter config: https://github.com/Lightning-AI/lightning/blob/35ec79ad1f75790767a6857637c9bbe052e47b58/.github/labeler.yml#L1-L3

### Additional context
There's a similar comment in #365 authored by @1bberto

> for some reason the labels are not being added to the PR and are also being **removed** when I add the labels manually

**Comment by ford-at-aws** [comment] 2022-10-03 15:15
Any update on this issue?

**Comment by MaksimZhukov** [comment] 2022-12-12 08:50
Hello everyone! 
I am closing this issue as a duplicate of [this one](https://github.com/actions/labeler/issues/112). Please monitor the bug status in scope of that issue.

**Closed by MaksimZhukov** 2022-12-12 08:50 UTC
Labels: duplicate
