### ISSUE TITLE
Array with all property

### ISSUE THREAD

**Issue by Waltari10** [actions/labeler#266] opened 2021-10-26 14:18 UTC
I'm trying to add a label to PR:s only if certain files have changed.

I tried the following:
```
# Automatically exclude changes from release notes
ignore-for-release:
  - all: ['**/*.spec.ts', '**/*.md', '**/*.test.ts', '.github/**.*', '.vscode/**.*']
```

However it seems this never triggers.

Basically I would like ANY globs to match against ALL changed paths. 🤔 

For example, if there are changes to ".md" files and ".github/**" files I would like it to add "ignore-for-release" tag.

But if there are change to ".md" files, ".github/**" files AND ".tsx" files then I don't want it to add the label.

Is this possible with the current feature set?

**Comment by tkbeal** [comment] 2022-01-31 22:39
I'm also new to this action, but I think your current config will fire when *all* the files changed match your match object, which is not what you want. I think you maybe should put the OR logic into top-level list and add an all to your label match. 
```
ignore-for-release:
- '.github/**/*'
- '**/*.md'
- '**/*.test.ts'
- all: ['!**/*.tsx']
```

**Comment by dfandrich** [comment] 2023-01-20 21:23
This looks like a dupe of #423.

**Comment by MaksimZhukov** [comment] 2023-07-04 14:03
Hello @Waltari10!
Unfortunately, this functionality is not available at the moment. We are considering adding it to a new major release.
I am closing this issue. Please track the progress of this feature request in scope of [this issue](https://github.com/actions/labeler/issues/423).

**Closed by MaksimZhukov** 2023-07-04 14:03 UTC
Labels: question
