### ISSUE TITLE
Labeler is not labeling PRs

### ISSUE THREAD

**Issue by Kitzunu** [actions/labeler#107] opened 2020-10-19 12:19 UTC
Hey! 

I am using this action on an open-source repository with these settings:

```yml


DB:
  - data/**/*.sql

CORE:
  - any: ['src/**/*.cpp', 'src/**/*.h', '!src/server/scripts/*']

Script:
  - src/server/scripts/**/*.cpp
  - src/server/scripts/**/*.h

Documentation:
  - ./*.md

Bash:
  - ./*.sh

Cmake:
  - ./*.cmake

Workflow:
  - .github/workflows/*
```
```yml
name: "Pull Request Labeler"
on: [pull_request]

jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        sync-labels: true
```

On the initial PR to implement this it did label on what was changed no problems, but now when I update PRs to latest master the action will run, however, it will not label anything.

Is there something in my settings that I have messed up for it to correctly label PRs?

**Comment by Kitzunu** [comment] 2020-10-21 08:24
Okay, so I tested a few other directories and it looks like the "Workflow", "Scripts" and "DB" labels works, however, none of the ./* paths or paths inside the *any* will get a label on them

**Comment by mgan59** [comment] 2020-10-24 13:44
Just came here, and believe my rule:

```yaml
docs:
  - ./*.md
  - docs/*.md
  - docs/**/*.md
```

having a similar issue.  Labels for things in `docs/` but for instance changes to the root `readme.md` don't get labeled.

**Comment by kenbalto** [comment] 2020-10-30 14:10
Has anyone found a fix for this?

**Comment by Kitzunu** [comment] 2020-11-12 16:07
Okay I changed to two conditions as this
```yml
  - any: ['src/**/*', '!src/server/scripts/*']
```
Now it seems to be working as it should

**Comment by MaksimZhukov** [comment] 2022-12-12 07:00
Hello everyone!
This issue has been open for a year without any activity, so I'm going to close it as stale.
Please feel free to contact us if the issue is still relevant to you and we will reopen it.
Thanks!

**Closed by MaksimZhukov** 2022-12-12 07:00 UTC

**Comment by brysonjonesy** [comment] 2023-04-12 22:09
> On the initial PR to implement this it did label on what was changed no problems, but now when I update PRs to latest master the action will run, however, it will not label anything.

Same thing is happening to us
