### ISSUE TITLE
Bug: Label not apply when the change file matched to the match object

### ISSUE THREAD

**Issue by liya2017** [actions/labeler#415] opened 2022-08-10 03:01 UTC
The labeler.yaml defined like below:
```
underlying:
- any: ['core/consensus/src/*', 'core/mempool/src/*', 'core/executor/src/*', 'core/network/src/*', 'core/storage/src/*']
```

But the label not apply since the labeler thinks the change file not matched to  match object.

The change files like the debug log:
<img width="990" alt="image" src="https://user-images.githubusercontent.com/32123500/183801169-efa1c2fa-a595-45cb-8b3a-b7f69f1f3d37.png">

**Comment by MaksimZhukov** [comment] 2022-10-28 14:45
Hello @liya2017! 
I could not reproduce your issue. Judging by your logs, the `core/consensus/src/*` glob didn't match changes in the `core/api/src/adapter.rs` file, but it did for the `core/consensus/src/adapter.rs`. 

Could you please provide us with a link to a PR or a workflow run for further investigation if the issue is still relevant to you?

**Comment by MaksimZhukov** [comment] 2022-12-12 07:57
I’m closing the issue. Please provide us with information for further investigation and we will reopen it.

**Closed by MaksimZhukov** 2022-12-12 07:57 UTC
