### ISSUE TITLE
Labeler is syncing labels when sync-labels property is false

### ISSUE THREAD

**Issue by joncolas** [actions/labeler#104] opened 2020-10-01 12:39 UTC
Having created a branch with an empty commit, I create a PR with some tags added manually, then labeler github action is executed and removes (synchronize) all labels that I have defined in the file labeler.yml complying with the file rules.

I tried with `sync-labels` unset and set to `false`.

github action log:
```
Run actions/labeler@main
  with:
    repo-token: ***
    sync-labels: false
    configuration-path: .github/labeler.yml
```

![image](https://user-images.githubusercontent.com/8049798/94809720-4edd6300-03f3-11eb-91fc-18355f31e56c.png)

I think this should not happen with the `sync-labels` set to `false`, any advice?

**Comment by Holzhaus** [comment] 2020-10-24 12:59
I can reproduce it. I'll try to mitigate the issue using the workaround from https://github.com/wesnoth/wesnoth/commit/958c82d0867568057caaf58356502ec8c87d8366.

**Comment by MaksimZhukov** [comment] 2022-12-12 08:50
Hello everyone! 
I am closing this issue as a duplicate of [this one](https://github.com/actions/labeler/issues/112). Please monitor the bug status in scope of that issue.

**Closed by MaksimZhukov** 2022-12-12 08:50 UTC
